# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: RoverChallenge 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "RoverChallenge".freeze
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Derrick".freeze]
  s.date = "2021-04-12"
  s.description = "Calculates the locations of rovers placed on a rectangular plane provided with the size of the plane, the starting position, starting directions and movement instructions for each rover.".freeze
  s.email = "barlow.dw@gmail.com".freeze
  s.executables = ["rover_challenge".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".github/workflows/ruby.yml",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "RoverChallenge.gemspec",
    "VERSION",
    "bin/rover_challenge",
    "lib/rover_challenge.rb",
    "lib/rover_challenge/cli.rb",
    "lib/rover_challenge/mission.rb",
    "lib/rover_challenge/mission_factory.rb",
    "lib/rover_challenge/rover.rb",
    "spec/rover_challenge/mission_factory_spec.rb",
    "spec/rover_challenge/missions_spec.rb",
    "spec/rover_challenge/rover_spec.rb",
    "spec/spec_helper.rb",
    "test.txt"
  ]
  s.homepage = "http://github.com/barlow.dw@gmail.com/roverchallenge".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.4".freeze
  s.summary = "Rover challenge".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 2.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

